CREATE TABLE IF NOT EXISTS users (
	id VARCHAR(21) PRIMARY KEY NOT NULL,
	name VARCHAR(40) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
)
