CREATE TABLE IF NOT EXISTS teams (
	id VARCHAR(21) PRIMARY KEY NOT NULL,
	name VARCHAR(30) NOT NULL,
	slug VARCHAR(30) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	owner_id NOT NULL REFERENCES "users"(user_id)
)
