CREATE TABLE IF NOT EXISTS teams (
	id BIGINT PRIMARY KEY NOT NULL,
	name VARCHAR(30) NOT NULL,
	slug VARCHAR(30) NOT NULL,
	logo TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	owner_id BIGINT NOT NULL REFERENCES "users"(id)
)
