CREATE TABLE IF NOT EXISTS teams (
	id VARCHAR(21) PRIMARY KEY NOT NULL,
	name VARCHAR(30) NOT NULL,
	slug VARCHAR(30) NOT NULL,
	logo TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	owner_id VARCHAR(21) NOT NULL REFERENCES "users"(id)
)
