CREATE TABLE IF NOT EXISTS roles (
	id BIGINT PRIMARY KEY NOT NULL,
	team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE,
	name VARCHAR(30) NOT NULL,
	is_default BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UNIQUE (team_id, name)
)
