//! Row type and queries for the `applications` table.
//!
//! Mirrors [`podkit_core::domain::application::entity::Application`], except
//! `build_strategy` stays a raw `String` here and `cpu_limit` is stored as
//! `f32` (Postgres `real`) instead of the domain's `f64`.

use sqlx::prelude::FromRow;
use time::OffsetDateTime;

use crate::{DatabaseError, DbExecutor};

/// Row from the `applications` table.
#[derive(Debug, Clone, FromRow)]
pub struct ApplicationModel {
	/// Primary key, matches the domain entity's id.
	pub id: i64,
	/// Owning project.
	pub project_id: i64,
	/// Server the app is deployed on.
	pub server_id: i64,
	/// Human-readable name.
	pub name: String,
	/// Unique per server; used to derive the app's subdomain.
	pub slug: String,
	/// Git repository URL to clone from.
	pub repo_url: String,
	/// Git branch, tag, or ref to deploy.
	pub git_ref: String,
	/// age-encrypted deploy key. `None` for public repos.
	pub deploy_key: Option<Vec<u8>>,
	/// Raw storage form of [`BuildStrategy`](podkit_core::domain::application::entity::BuildStrategy), see its `as_str`/`parse`.
	pub build_strategy: String,
	/// Path to the Dockerfile within the repo, when building from one.
	pub dockerfile_path: String,
	/// Port the container listens on.
	pub container_port: i32,
	/// age-encrypted webhook deploy secret. `None` disables webhook deploys.
	pub webhook_secret: Option<Vec<u8>>,
	/// Memory limit in megabytes. `None` means unlimited.
	pub memory_limit_mb: Option<i32>,
	/// Fractional CPU cores. `None` means unlimited.
	pub cpu_limit: Option<f32>,
	/// Row creation timestamp.
	pub created_at: OffsetDateTime,
	/// Last update timestamp.
	pub updated_at: OffsetDateTime,
}

/// Fields needed to insert a new application row.
#[derive(Debug)]
pub struct NewApplication {
	/// Primary key; generated by the caller (snowflake id), not the database.
	pub id: i64,
	/// Owning project.
	pub project_id: i64,
	/// Server to deploy on.
	pub server_id: i64,
	/// Human-readable name.
	pub name: String,
	/// Unique per server; used to derive the app's subdomain.
	pub slug: String,
	/// Git repository URL to clone from.
	pub repo_url: String,
	/// Git branch, tag, or ref to deploy.
	pub git_ref: String,
	/// age-encrypted deploy key. `None` for public repos.
	pub deploy_key: Option<Vec<u8>>,
	/// Raw storage form of the build strategy.
	pub build_strategy: String,
	/// Path to the Dockerfile within the repo, when building from one.
	pub dockerfile_path: String,
	/// Port the container listens on.
	pub container_port: i32,
	/// age-encrypted webhook deploy secret. `None` disables webhook deploys.
	pub webhook_secret: Option<Vec<u8>>,
	/// Memory limit in megabytes. `None` means unlimited.
	pub memory_limit_mb: Option<i32>,
	/// Fractional CPU cores. `None` means unlimited.
	pub cpu_limit: Option<f32>,
}

/// Same editable fields as `NewApplication`, minus the ones fixed at
/// creation (`project_id`, `server_id`, `webhook_secret`).
#[derive(Debug)]
pub struct ApplicationUpdate {
	/// Human-readable name.
	pub name: String,
	/// Unique per server; used to derive the app's subdomain.
	pub slug: String,
	/// Git repository URL to clone from.
	pub repo_url: String,
	/// Git branch, tag, or ref to deploy.
	pub git_ref: String,
	/// Resolved by the caller before this call, `None` means "no deploy
	/// key" (public repo), not "leave unchanged"; the route handler is
	/// responsible for defaulting to the existing stored value when the
	/// request didn't ask to change it.
	pub deploy_key: Option<Vec<u8>>,
	/// Raw storage form of the build strategy.
	pub build_strategy: String,
	/// Path to the Dockerfile within the repo, when building from one.
	pub dockerfile_path: String,
	/// Port the container listens on.
	pub container_port: i32,
	/// Memory limit in megabytes. `None` means unlimited.
	pub memory_limit_mb: Option<i32>,
	/// Fractional CPU cores. `None` means unlimited.
	pub cpu_limit: Option<f32>,
}

impl ApplicationModel {
	/// Inserts a new application row and returns it.
	///
	/// # Errors
	/// Returns an error if the insert fails.
	pub async fn create<'e>(
		exec: impl DbExecutor<'e>,
		new: NewApplication,
	) -> Result<Self, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			r#"
				INSERT INTO applications
					(id, project_id, server_id, name, slug, repo_url, git_ref, deploy_key, build_strategy, dockerfile_path, container_port, webhook_secret, memory_limit_mb, cpu_limit)
				VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
				RETURNING *
			"#,
			new.id,
			new.project_id,
			new.server_id,
			new.name,
			new.slug,
			new.repo_url,
			new.git_ref,
			new.deploy_key,
			new.build_strategy,
			new.dockerfile_path,
			new.container_port,
			new.webhook_secret,
			new.memory_limit_mb,
			new.cpu_limit
		)
		.fetch_one(exec)
		.await?)
	}

	/// Updates the editable fields of an application and bumps `updated_at`.
	///
	/// # Errors
	/// Returns an error if the update fails.
	pub async fn update<'e>(
		exec: impl DbExecutor<'e>,
		id: i64,
		update: ApplicationUpdate,
	) -> Result<Self, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			r#"
				UPDATE applications
				SET name = $2, slug = $3, repo_url = $4, git_ref = $5,
					deploy_key = $6, build_strategy = $7, dockerfile_path = $8,
					container_port = $9, memory_limit_mb = $10, cpu_limit = $11,
					updated_at = NOW()
				WHERE id = $1
				RETURNING *
			"#,
			id,
			update.name,
			update.slug,
			update.repo_url,
			update.git_ref,
			update.deploy_key,
			update.build_strategy,
			update.dockerfile_path,
			update.container_port,
			update.memory_limit_mb,
			update.cpu_limit
		)
		.fetch_one(exec)
		.await?)
	}

	/// Looks up an application by id.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn find_by_id<'e>(
		exec: impl DbExecutor<'e>,
		id: i64,
	) -> Result<Option<Self>, DatabaseError> {
		Ok(
			sqlx::query_as!(Self, "SELECT * FROM applications WHERE id = $1", id)
				.fetch_optional(exec)
				.await?,
		)
	}

	/// Lists every application belonging to a project.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn list_by_project<'e>(
		exec: impl DbExecutor<'e>,
		project_id: i64,
	) -> Result<Vec<Self>, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			"SELECT * FROM applications WHERE project_id = $1",
			project_id
		)
		.fetch_all(exec)
		.await?)
	}

	/// Lists every application deployed on a server.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn list_by_server<'e>(
		exec: impl DbExecutor<'e>,
		server_id: i64,
	) -> Result<Vec<Self>, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			"SELECT * FROM applications WHERE server_id = $1",
			server_id
		)
		.fetch_all(exec)
		.await?)
	}

	/// Deletes an application by id.
	///
	/// # Errors
	/// Returns an error if the delete fails.
	pub async fn delete<'e>(exec: impl DbExecutor<'e>, id: i64) -> Result<(), DatabaseError> {
		sqlx::query!("DELETE FROM applications WHERE id = $1", id)
			.execute(exec)
			.await?;
		Ok(())
	}
}
