//! Row type and queries for the `custom_domains` table.
//!
//! Mirrors [`podkit_core::domain::custom_domain::entity::CustomDomain`] field for field.

use sqlx::prelude::FromRow;
use time::OffsetDateTime;

use crate::{DatabaseError, DbExecutor};

/// Row from the `custom_domains` table.
#[derive(Debug, Clone, FromRow)]
pub struct CustomDomainModel {
	/// Primary key, matches the domain entity's id.
	pub id: i64,
	/// The application this domain routes to.
	pub application_id: i64,
	/// The custom hostname, unique across the whole install.
	pub hostname: String,
	/// Row creation timestamp.
	pub created_at: OffsetDateTime,
	/// Last update timestamp.
	pub updated_at: OffsetDateTime,
}

/// Fields needed to insert a new custom domain row.
#[derive(Debug)]
pub struct NewCustomDomain {
	/// Primary key; generated by the caller (snowflake id), not the database.
	pub id: i64,
	/// The application this domain routes to.
	pub application_id: i64,
	/// The custom hostname.
	pub hostname: String,
}

impl CustomDomainModel {
	/// Inserts a new custom domain row and returns it.
	///
	/// # Errors
	/// Returns an error if the insert fails.
	pub async fn create<'e>(
		exec: impl DbExecutor<'e>,
		new: NewCustomDomain,
	) -> Result<Self, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			r#"
				INSERT INTO custom_domains (id, application_id, hostname)
				VALUES ($1, $2, $3)
				RETURNING *
			"#,
			new.id,
			new.application_id,
			new.hostname
		)
		.fetch_one(exec)
		.await?)
	}

	/// Looks up a custom domain by id.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn find_by_id<'e>(
		exec: impl DbExecutor<'e>,
		id: i64,
	) -> Result<Option<Self>, DatabaseError> {
		Ok(
			sqlx::query_as!(Self, "SELECT * FROM custom_domains WHERE id = $1", id)
				.fetch_optional(exec)
				.await?,
		)
	}

	/// Lists every custom domain attached to an application, ordered by hostname.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn list_by_application<'e>(
		exec: impl DbExecutor<'e>,
		application_id: i64,
	) -> Result<Vec<Self>, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			"SELECT * FROM custom_domains WHERE application_id = $1 ORDER BY hostname",
			application_id
		)
		.fetch_all(exec)
		.await?)
	}

	/// Deletes a custom domain by id.
	///
	/// # Errors
	/// Returns an error if the delete fails.
	pub async fn delete<'e>(exec: impl DbExecutor<'e>, id: i64) -> Result<(), DatabaseError> {
		sqlx::query!("DELETE FROM custom_domains WHERE id = $1", id)
			.execute(exec)
			.await?;
		Ok(())
	}
}
