//! Row type and queries for the `deployments` table.
//!
//! Mirrors [`podkit_core::domain::deployment::entity::Deployment`]; `status`
//! stays a raw `String` here, see
//! [`DeploymentStatus`](podkit_core::domain::deployment::entity::DeploymentStatus)
//! for the `as_str`/`parse` round trip.

use sqlx::prelude::FromRow;
use time::OffsetDateTime;

use crate::{DatabaseError, DbExecutor};

/// Row from the `deployments` table.
#[derive(Debug, Clone, FromRow)]
pub struct DeploymentModel {
	/// Primary key, matches the domain entity's id.
	pub id: i64,
	/// The application this is a deployment attempt for.
	pub application_id: i64,
	/// Raw storage form of the deployment status.
	pub status: String,
	/// Git commit sha being deployed, once known.
	pub commit_sha: Option<String>,
	/// Tag of the image built for this deployment, once built.
	pub image_tag: Option<String>,
	/// Id of the running container, once created.
	pub container_id: Option<String>,
	/// Failure detail, set once the deployment fails.
	pub error_message: Option<String>,
	/// User who triggered this deployment, if any.
	pub triggered_by: Option<i64>,
	/// Row creation timestamp.
	pub created_at: OffsetDateTime,
	/// When the build started, once it starts.
	pub started_at: Option<OffsetDateTime>,
	/// When the attempt reached a terminal state.
	pub finished_at: Option<OffsetDateTime>,
}

/// Fields needed to insert a new deployment row, always starting in the
/// `queued` state.
#[derive(Debug)]
pub struct NewDeployment {
	/// Primary key; generated by the caller (snowflake id), not the database.
	pub id: i64,
	/// The application being deployed.
	pub application_id: i64,
	/// User who triggered this deployment, if any.
	pub triggered_by: Option<i64>,
}

/// Fields for advancing a deployment through its lifecycle.
#[derive(Debug)]
pub struct DeploymentUpdate {
	/// Row to update.
	pub id: i64,
	/// New raw status value.
	pub status: String,
	/// Git commit sha being deployed, once known.
	pub commit_sha: Option<String>,
	/// Tag of the image built for this deployment, once built.
	pub image_tag: Option<String>,
	/// Id of the running container, once created.
	pub container_id: Option<String>,
	/// Failure detail, set once the deployment fails.
	pub error_message: Option<String>,
	/// When the build started, once it starts.
	pub started_at: Option<OffsetDateTime>,
	/// When the attempt reached a terminal state.
	pub finished_at: Option<OffsetDateTime>,
}

impl DeploymentModel {
	/// Inserts a new deployment row and returns it.
	///
	/// # Errors
	/// Returns an error if the insert fails.
	pub async fn create<'e>(
		exec: impl DbExecutor<'e>,
		new: NewDeployment,
	) -> Result<Self, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			r#"
				INSERT INTO deployments (id, application_id, triggered_by)
				VALUES ($1, $2, $3)
				RETURNING *
			"#,
			new.id,
			new.application_id,
			new.triggered_by
		)
		.fetch_one(exec)
		.await?)
	}

	/// Applies a status/result update to an existing deployment row.
	///
	/// # Errors
	/// Returns an error if the update fails.
	pub async fn update<'e>(
		exec: impl DbExecutor<'e>,
		update: DeploymentUpdate,
	) -> Result<Self, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			r#"
				UPDATE deployments SET
					status = $2,
					commit_sha = $3,
					image_tag = $4,
					container_id = $5,
					error_message = $6,
					started_at = $7,
					finished_at = $8
				WHERE id = $1
				RETURNING *
			"#,
			update.id,
			update.status,
			update.commit_sha,
			update.image_tag,
			update.container_id,
			update.error_message,
			update.started_at,
			update.finished_at
		)
		.fetch_one(exec)
		.await?)
	}

	/// Looks up a deployment by id.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn find_by_id<'e>(
		exec: impl DbExecutor<'e>,
		id: i64,
	) -> Result<Option<Self>, DatabaseError> {
		Ok(
			sqlx::query_as!(Self, "SELECT * FROM deployments WHERE id = $1", id)
				.fetch_optional(exec)
				.await?,
		)
	}

	/// Lists every deployment attempt for an application, newest first.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn list_by_application<'e>(
		exec: impl DbExecutor<'e>,
		application_id: i64,
	) -> Result<Vec<Self>, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			"SELECT * FROM deployments WHERE application_id = $1 ORDER BY created_at DESC",
			application_id
		)
		.fetch_all(exec)
		.await?)
	}

	/// Lists every deployment currently in the `running` state.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn list_running<'e>(exec: impl DbExecutor<'e>) -> Result<Vec<Self>, DatabaseError> {
		Ok(
			sqlx::query_as!(Self, "SELECT * FROM deployments WHERE status = 'running'")
				.fetch_all(exec)
				.await?,
		)
	}
}
