//! Row type and queries for the `env_vars` table.
//!
//! Mirrors [`podkit_core::domain::env_var::entity::EnvVar`] field for field.

use sqlx::prelude::FromRow;
use time::OffsetDateTime;

use crate::{DatabaseError, DbExecutor};

/// Row from the `env_vars` table.
#[derive(Debug, Clone, FromRow)]
pub struct EnvVarModel {
	/// Primary key, matches the domain entity's id.
	pub id: i64,
	/// The application this variable is injected into.
	pub application_id: i64,
	/// Variable name.
	pub key: String,
	/// age-encrypted value; never stored or returned as plaintext.
	pub value: Vec<u8>,
	/// Row creation timestamp.
	pub created_at: OffsetDateTime,
	/// Last update timestamp.
	pub updated_at: OffsetDateTime,
}

/// Fields needed to insert or update an env var row.
#[derive(Debug)]
pub struct NewEnvVar {
	/// Primary key; generated by the caller (snowflake id), not the database.
	pub id: i64,
	/// The application this variable is injected into.
	pub application_id: i64,
	/// Variable name.
	pub key: String,
	/// age-encrypted value.
	pub value: Vec<u8>,
}

impl EnvVarModel {
	/// Inserts a new env var, or updates the value (and id, so the caller's
	/// id wins on first-insert but a re-set of the same key keeps its
	/// original row identity) if `(application_id, key)` already exists.
	///
	/// # Errors
	/// Returns an error if the insert fails.
	pub async fn upsert<'e>(
		exec: impl DbExecutor<'e>,
		new: NewEnvVar,
	) -> Result<Self, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			r#"
				INSERT INTO env_vars (id, application_id, key, value)
				VALUES ($1, $2, $3, $4)
				ON CONFLICT (application_id, key)
				DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
				RETURNING *
			"#,
			new.id,
			new.application_id,
			new.key,
			new.value
		)
		.fetch_one(exec)
		.await?)
	}

	/// Looks up an env var by id.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn find_by_id<'e>(
		exec: impl DbExecutor<'e>,
		id: i64,
	) -> Result<Option<Self>, DatabaseError> {
		Ok(
			sqlx::query_as!(Self, "SELECT * FROM env_vars WHERE id = $1", id)
				.fetch_optional(exec)
				.await?,
		)
	}

	/// Lists every env var set on an application, ordered by key.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn list_by_application<'e>(
		exec: impl DbExecutor<'e>,
		application_id: i64,
	) -> Result<Vec<Self>, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			"SELECT * FROM env_vars WHERE application_id = $1 ORDER BY key",
			application_id
		)
		.fetch_all(exec)
		.await?)
	}

	/// Deletes an env var by id.
	///
	/// # Errors
	/// Returns an error if the delete fails.
	pub async fn delete<'e>(exec: impl DbExecutor<'e>, id: i64) -> Result<(), DatabaseError> {
		sqlx::query!("DELETE FROM env_vars WHERE id = $1", id)
			.execute(exec)
			.await?;
		Ok(())
	}
}
