//! Row type and queries for the `projects` table.
//!
//! Mirrors [`podkit_core::domain::project::entity::Project`] field for field.

use sqlx::prelude::FromRow;
use time::OffsetDateTime;

use crate::{DatabaseError, DbExecutor};

/// Row from the `projects` table.
#[derive(Debug, Clone, FromRow)]
pub struct ProjectModel {
	/// Primary key, matches the domain entity's id.
	pub id: i64,
	/// The team that owns this project.
	pub team_id: i64,
	/// Display name.
	pub name: String,
	/// URL-safe unique identifier, scoped to the team.
	pub slug: String,
	/// Row creation timestamp.
	pub created_at: OffsetDateTime,
	/// Last update timestamp.
	pub updated_at: OffsetDateTime,
}

/// Fields needed to insert a new project row.
#[derive(Debug)]
pub struct NewProject {
	/// Primary key; generated by the caller (snowflake id), not the database.
	pub id: i64,
	/// The team that owns this project.
	pub team_id: i64,
	/// Display name.
	pub name: String,
	/// URL-safe unique identifier, scoped to the team.
	pub slug: String,
}

impl ProjectModel {
	/// Inserts a new project row and returns it.
	///
	/// # Errors
	/// Returns an error if the insert fails.
	pub async fn create<'e>(
		exec: impl DbExecutor<'e>,
		new: NewProject,
	) -> Result<Self, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			r#"
				INSERT INTO projects (id, team_id, name, slug)
				VALUES ($1, $2, $3, $4)
				RETURNING *
			"#,
			new.id,
			new.team_id,
			new.name,
			new.slug
		)
		.fetch_one(exec)
		.await?)
	}

	/// Looks up a project by id.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn find_by_id<'e>(
		exec: impl DbExecutor<'e>,
		id: i64,
	) -> Result<Option<Self>, DatabaseError> {
		Ok(
			sqlx::query_as!(Self, "SELECT * FROM projects WHERE id = $1", id)
				.fetch_optional(exec)
				.await?,
		)
	}

	/// Lists every project owned by a team.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn list_by_team<'e>(
		exec: impl DbExecutor<'e>,
		team_id: i64,
	) -> Result<Vec<Self>, DatabaseError> {
		Ok(
			sqlx::query_as!(Self, "SELECT * FROM projects WHERE team_id = $1", team_id)
				.fetch_all(exec)
				.await?,
		)
	}

	/// Deletes a project by id.
	///
	/// # Errors
	/// Returns an error if the delete fails.
	pub async fn delete<'e>(exec: impl DbExecutor<'e>, id: i64) -> Result<(), DatabaseError> {
		sqlx::query!("DELETE FROM projects WHERE id = $1", id)
			.execute(exec)
			.await?;
		Ok(())
	}
}
