//! Row type and queries for the `roles` table.
//!
//! Mirrors [`podkit_core::domain::role::entity::Role`] field for field.

use sqlx::prelude::FromRow;
use time::OffsetDateTime;

use crate::{DatabaseError, DbExecutor};

/// Row from the `roles` table.
#[derive(Debug, Clone, FromRow)]
pub struct RoleModel {
	/// Primary key, matches the domain entity's id.
	pub id: i64,
	/// `None` for a built-in/global role, shared across every team.
	pub team_id: Option<i64>,
	/// Display name, e.g. "admin" or "viewer".
	pub name: String,
	/// Whether this role is assigned by default to new team members.
	pub is_default: bool,
	/// Row creation timestamp.
	pub created_at: OffsetDateTime,
}

/// Fields needed to insert a new role row.
#[derive(Debug)]
pub struct NewRole {
	/// Primary key; generated by the caller (snowflake id), not the database.
	pub id: i64,
	/// `None` for a built-in/global role, shared across every team.
	pub team_id: Option<i64>,
	/// Display name.
	pub name: String,
	/// Whether this role is assigned by default to new team members.
	pub is_default: bool,
}

impl RoleModel {
	/// Looks up a role by id.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn find_by_id<'e>(
		exec: impl DbExecutor<'e>,
		id: i64,
	) -> Result<Option<Self>, DatabaseError> {
		Ok(
			sqlx::query_as!(Self, "SELECT * FROM roles WHERE id = $1", id)
				.fetch_optional(exec)
				.await?,
		)
	}

	/// Looks up a built-in (global) role by name, e.g. `"Owner"`.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn find_builtin_by_name<'e>(
		exec: impl DbExecutor<'e>,
		name: &str,
	) -> Result<Option<Self>, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			"SELECT * FROM roles WHERE team_id IS NULL AND name = $1",
			name
		)
		.fetch_optional(exec)
		.await?)
	}

	/// Lists every role usable by a team: built-in roles plus the team's own.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn list_for_team<'e>(
		exec: impl DbExecutor<'e>,
		team_id: i64,
	) -> Result<Vec<Self>, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			"SELECT * FROM roles WHERE team_id IS NULL OR team_id = $1",
			team_id
		)
		.fetch_all(exec)
		.await?)
	}

	/// Inserts a new role row and returns it.
	///
	/// # Errors
	/// Returns an error if the insert fails.
	pub async fn create<'e>(
		exec: impl DbExecutor<'e>,
		new: NewRole,
	) -> Result<Self, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			r#"
				INSERT INTO roles (id, team_id, name, is_default)
				VALUES ($1, $2, $3, $4)
				RETURNING *
			"#,
			new.id,
			new.team_id,
			new.name,
			new.is_default
		)
		.fetch_one(exec)
		.await?)
	}

	/// Deletes a role by id.
	///
	/// # Errors
	/// Returns an error if the delete fails.
	pub async fn delete<'e>(exec: impl DbExecutor<'e>, id: i64) -> Result<(), DatabaseError> {
		sqlx::query!("DELETE FROM roles WHERE id = $1", id)
			.execute(exec)
			.await?;
		Ok(())
	}
}
