//! Row type and queries for the `servers` table.
//!
//! Mirrors [`podkit_core::domain::server::entity::Server`]; `status` stays a
//! raw `String` here, see
//! [`ServerStatus`](podkit_core::domain::server::entity::ServerStatus) for
//! the `as_str`/`parse` round trip.

use sqlx::prelude::FromRow;
use time::OffsetDateTime;

use crate::{DatabaseError, DbExecutor};

/// Row from the `servers` table.
#[derive(Debug, Clone, FromRow)]
pub struct ServerModel {
	/// Primary key, matches the domain entity's id.
	pub id: i64,
	/// The team that owns this server.
	pub team_id: i64,
	/// Human-readable name.
	pub name: String,
	/// Hostname or IP podkit connects to.
	pub hostname: String,
	/// SSH port, unused for the local server.
	pub ssh_port: i32,
	/// SSH username. `None` iff `is_local`.
	pub ssh_user: Option<String>,
	/// age-encrypted private key bytes. `None` iff `is_local`.
	pub ssh_private_key: Option<Vec<u8>>,
	/// Path to the podman socket on the target host.
	pub podman_socket_path: String,
	/// True for the single podkit-managed local server; false for remote,
	/// SSH-reached hosts.
	pub is_local: bool,
	/// Raw storage form of the server's connectivity status.
	pub status: String,
	/// Row creation timestamp.
	pub created_at: OffsetDateTime,
	/// Last update timestamp.
	pub updated_at: OffsetDateTime,
}

/// Fields needed to insert a new server row.
#[derive(Debug)]
pub struct NewServer {
	/// Primary key; generated by the caller (snowflake id), not the database.
	pub id: i64,
	/// The team that owns this server.
	pub team_id: i64,
	/// Human-readable name.
	pub name: String,
	/// Hostname or IP podkit connects to.
	pub hostname: String,
	/// SSH port, unused for the local server.
	pub ssh_port: i32,
	/// SSH username. `None` iff `is_local`.
	pub ssh_user: Option<String>,
	/// age-encrypted private key bytes. `None` iff `is_local`.
	pub ssh_private_key: Option<Vec<u8>>,
	/// Path to the podman socket on the target host.
	pub podman_socket_path: String,
	/// True for the single podkit-managed local server; false for remote,
	/// SSH-reached hosts.
	pub is_local: bool,
	/// Raw storage form of the initial connectivity status.
	pub status: String,
}

impl ServerModel {
	/// Inserts a new server row and returns it.
	///
	/// # Errors
	/// Returns an error if the insert fails.
	pub async fn create<'e>(
		exec: impl DbExecutor<'e>,
		new: NewServer,
	) -> Result<Self, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			r#"
				INSERT INTO servers
					(id, team_id, name, hostname, ssh_port, ssh_user, ssh_private_key, podman_socket_path, is_local, status)
				VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
				RETURNING *
			"#,
			new.id,
			new.team_id,
			new.name,
			new.hostname,
			new.ssh_port,
			new.ssh_user,
			new.ssh_private_key,
			new.podman_socket_path,
			new.is_local,
			new.status
		)
		.fetch_one(exec)
		.await?)
	}

	/// Looks up a server by id.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn find_by_id<'e>(
		exec: impl DbExecutor<'e>,
		id: i64,
	) -> Result<Option<Self>, DatabaseError> {
		Ok(
			sqlx::query_as!(Self, "SELECT * FROM servers WHERE id = $1", id)
				.fetch_optional(exec)
				.await?,
		)
	}

	/// Lists every server owned by a team.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn list_by_team<'e>(
		exec: impl DbExecutor<'e>,
		team_id: i64,
	) -> Result<Vec<Self>, DatabaseError> {
		Ok(
			sqlx::query_as!(Self, "SELECT * FROM servers WHERE team_id = $1", team_id)
				.fetch_all(exec)
				.await?,
		)
	}

	/// Deletes a server by id.
	///
	/// # Errors
	/// Returns an error if the delete fails.
	pub async fn delete<'e>(exec: impl DbExecutor<'e>, id: i64) -> Result<(), DatabaseError> {
		sqlx::query!("DELETE FROM servers WHERE id = $1", id)
			.execute(exec)
			.await?;
		Ok(())
	}
}
