//! Row type and queries for the `team_members` table.
//!
//! Mirrors [`podkit_core::domain::team_member::entity::TeamMember`] field for field.

use sqlx::prelude::FromRow;
use time::OffsetDateTime;

use crate::{DatabaseError, DbExecutor};

/// Row from the `team_members` table.
#[derive(Debug, Clone, FromRow)]
pub struct TeamMemberModel {
	/// Primary key, matches the domain entity's id.
	pub id: i64,
	/// The team joined.
	pub team_id: i64,
	/// The user who joined.
	pub user_id: i64,
	/// The role held within this team.
	pub role_id: i64,
	/// When the user joined the team.
	pub joined_at: OffsetDateTime,
}

/// Fields needed to insert a new team membership row.
#[derive(Debug)]
pub struct NewTeamMember {
	/// Primary key; generated by the caller (snowflake id), not the database.
	pub id: i64,
	/// The team to join.
	pub team_id: i64,
	/// The user joining.
	pub user_id: i64,
	/// The role to assign.
	pub role_id: i64,
}

impl TeamMemberModel {
	/// Inserts a membership, or updates its `role_id` if a row with this `id` already
	/// exists (this is how role changes are persisted: fetch, mutate then save).
	///
	/// # Errors
	/// Returns an error if the insert fails.
	pub async fn create<'e>(
		exec: impl DbExecutor<'e>,
		new: NewTeamMember,
	) -> Result<Self, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			r#"
				INSERT INTO team_members (id, team_id, user_id, role_id)
				VALUES ($1, $2, $3, $4)
				ON CONFLICT (id) DO UPDATE SET role_id = EXCLUDED.role_id
				RETURNING *
			"#,
			new.id,
			new.team_id,
			new.user_id,
			new.role_id
		)
		.fetch_one(exec)
		.await?)
	}

	/// Looks up a membership by team and user.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn find_by_team_and_user<'e>(
		exec: impl DbExecutor<'e>,
		team_id: i64,
		user_id: i64,
	) -> Result<Option<Self>, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			"SELECT * FROM team_members WHERE team_id = $1 AND user_id = $2",
			team_id,
			user_id
		)
		.fetch_optional(exec)
		.await?)
	}

	/// Lists every member of a team.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn list_by_team<'e>(
		exec: impl DbExecutor<'e>,
		team_id: i64,
	) -> Result<Vec<Self>, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			"SELECT * FROM team_members WHERE team_id = $1",
			team_id
		)
		.fetch_all(exec)
		.await?)
	}

	/// Reassigns a member's role within a team.
	///
	/// # Errors
	/// Returns an error if the update fails.
	pub async fn update_role<'e>(
		exec: impl DbExecutor<'e>,
		team_id: i64,
		user_id: i64,
		role_id: i64,
	) -> Result<(), DatabaseError> {
		sqlx::query!(
			"UPDATE team_members SET role_id = $1 WHERE team_id = $2 AND user_id = $3",
			role_id,
			team_id,
			user_id
		)
		.execute(exec)
		.await?;
		Ok(())
	}

	/// Removes a user's membership from a team.
	///
	/// # Errors
	/// Returns an error if the delete fails.
	pub async fn delete<'e>(
		exec: impl DbExecutor<'e>,
		team_id: i64,
		user_id: i64,
	) -> Result<(), DatabaseError> {
		sqlx::query!(
			"DELETE FROM team_members WHERE team_id = $1 AND user_id = $2",
			team_id,
			user_id
		)
		.execute(exec)
		.await?;
		Ok(())
	}
}
