//! Row type and queries for the `users` table.
//!
//! Mirrors [`podkit_core::domain::user::entity::User`]; `email` and
//! `password_hash` are stored as plain columns here, the domain wraps them
//! in `Email`/`PasswordHash` value objects for validation.

use sqlx::prelude::FromRow;
use time::OffsetDateTime;

use crate::{DatabaseError, DbExecutor};

/// Row from the `users` table.
#[derive(Debug, Clone, FromRow)]
pub struct UserModel {
	/// Primary key, matches the domain entity's id.
	pub id: i64,
	/// Display name (the domain entity's `display_name`).
	pub name: String,
	/// Normalized email, unique across users.
	pub email: String,
	/// Hashed password, never the plaintext.
	pub password_hash: String,
	/// Row creation timestamp.
	pub created_at: OffsetDateTime,
	/// Last update timestamp.
	pub updated_at: OffsetDateTime,
}

/// Fields needed to insert a new user row.
#[derive(Debug)]
pub struct NewUser {
	/// Primary key; generated by the caller (snowflake id), not the database.
	pub id: i64,
	/// Normalized email, unique across users.
	pub email: String,
	/// Display name.
	pub name: String,
	/// Hashed password, never the plaintext.
	pub password_hash: String,
}

impl UserModel {
	/// Creates a new user in the database
	///
	/// # Errors
	/// - Fails when theres an existing using with the same email.
	pub async fn create<'e>(
		exec: impl DbExecutor<'e>,
		new: NewUser,
	) -> Result<Self, DatabaseError> {
		Ok(sqlx::query_as!(
			Self,
			r#"
				INSERT INTO users (id, name, email, password_hash)
				VALUES ($1, $2, $3, $4)
				RETURNING *
			"#,
			new.id,
			new.name,
			new.email,
			new.password_hash
		)
		.fetch_one(exec)
		.await?)
	}

	/// Looks up a user by id.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn find_by_id<'e>(
		exec: impl DbExecutor<'e>,
		id: i64,
	) -> Result<Option<Self>, DatabaseError> {
		Ok(
			sqlx::query_as!(Self, "SELECT * FROM users WHERE id = $1", id)
				.fetch_optional(exec)
				.await?,
		)
	}

	/// Looks up a user by email.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn find_by_email<'e>(
		exec: impl DbExecutor<'e>,
		email: &str,
	) -> Result<Option<Self>, DatabaseError> {
		Ok(
			sqlx::query_as!(Self, "SELECT * FROM users WHERE email = $1", email)
				.fetch_optional(exec)
				.await?,
		)
	}

	/// Checks whether a user with this email already exists.
	///
	/// # Errors
	/// Returns an error if the query fails.
	pub async fn exists_by_email<'e>(
		exec: impl DbExecutor<'e>,
		email: &str,
	) -> Result<bool, DatabaseError> {
		let exists = sqlx::query_scalar!(
			r#"SELECT EXISTS(SELECT 1 FROM users WHERE email = $1) AS "exists!""#,
			email
		)
		.fetch_one(exec)
		.await?;
		Ok(exists)
	}

	/// Deletes a user by id.
	///
	/// # Errors
	/// Returns an error if the delete fails.
	pub async fn delete<'e>(exec: impl DbExecutor<'e>, id: i64) -> Result<(), DatabaseError> {
		sqlx::query!("DELETE FROM users WHERE id = $1", id)
			.execute(exec)
			.await?;
		Ok(())
	}
}
